[global]
trusted-host = pypi.python.org
               pypi.org
               files.pythonhosted.org
               nhindustries.corp
#index = https://pip.pkg.nhindustries.corp/pypi
#index-url = https://pip.pkg.nhindustries.corp/simple

