#!/bin/bash
echo "Use: source this file."
echo "source setenv.sh"
echo $PATH
#NODEPATH=/home/olivier/Software/node-v10.15.3-linux-x64/bin
#PATH=$NODEPATH:$PATH
PATH=/home/olivier/Software/node-v10.15.3-linux-x64/bin:$PATH
echo $PATH
#echo $NODEPATH
